# Generated by Django 2.2.5 on 2019-11-11 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191111_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='pet_images')),
                ('name', models.CharField(max_length=15)),
                ('pet_type', models.CharField(max_length=25)),
                ('breed', models.CharField(blank=True, max_length=25)),
                ('age', models.SmallIntegerField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='SearchInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('date_last_seen', models.DateField()),
                ('time_last_seen', models.TimeField()),
                ('last_known_location', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='SearchParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('search_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SearchInstance')),
            ],
        ),
        migrations.AddField(
            model_name='searchinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchinstance',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pet'),
        ),
    ]
