# Generated by Django 2.2.5 on 2019-11-11 17:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191111_0949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchParty',
            new_name='SearchPartyMembers',
        ),
        migrations.CreateModel(
            name='TrackingCoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('my_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('search_party_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SearchPartyMembers')),
            ],
        ),
    ]
