# Generated by Django 2.2.5 on 2019-11-12 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191111_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingcoord',
            old_name='search_party_members',
            new_name='search_party_member',
        ),
        migrations.CreateModel(
            name='StartEndPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start_or_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_party_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SearchPartyMembers')),
            ],
        ),
    ]
