# Generated by Django 2.2.5 on 2019-11-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191112_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.SmallIntegerField(blank=True, help_text='age in years'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1),
        ),
    ]
