# Generated by Django 2.2.5 on 2019-11-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191112_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(help_text='For example, dog or cat', max_length=25),
        ),
    ]
