# Generated by Django 2.2.5 on 2019-11-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191113_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_last_seen',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='time_last_seen',
            field=models.TimeField(),
        ),
    ]
