# Generated by Django 2.2.5 on 2019-11-28 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191113_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchpartymembers',
            name='pet',
        ),
        migrations.CreateModel(
            name='SearchPartyInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pet')),
            ],
        ),
        migrations.AddField(
            model_name='searchpartymembers',
            name='search_party_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.SearchPartyInstance'),
            preserve_default=False,
        ),
    ]
